<template>
  <div class="min-h-screen bg-blue-pale">
    <div class="max-w-4xl mx-auto px-4 py-12">
      <div class="mb-6">
        <NuxtLink to="/" class="flex items-center text-blue-navtext hover:text-blue-pricinghover transition-colors duration-200">
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back
        </NuxtLink>
      </div>
      
      <h1 class="text-4xl lg:text-5xl font-extrabold leading-tight mb-8 text-blue-h1">Privacy Policy</h1>
      <p class="text-blue-footertext mb-8 text-lg">Effective Date: {{ new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) }}</p>
      
      <div class="space-y-6 text-blue-footertext leading-relaxed">
        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">1. Introduction</h2>
          <p>Welcome to GPTOSS2 ("we," "our," or "us"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI-powered service (the "Service"). Your privacy is of the utmost importance to us.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">2. Information We Collect</h2>
          <p>To provide and improve our Service, we collect the following types of information:</p>
          <ul class="list-disc pl-6 mt-2 space-y-2">
            <li><strong class="text-blue-button">Account Information:</strong> When you register for an account, we collect your email address, password, and any profile details you choose to provide.</li>
            <li><strong class="text-blue-button">User Content:</strong> This includes the inputs you provide to the Service, such as text prompts and images you upload. It also includes the final outputs generated by the Service.</li>
            <li><strong class="text-blue-button">Usage Data:</strong> We automatically collect information about how you interact with our Service. This may include your IP address, browser type, device information, features used, and the time and date of your activities.</li>
            <li><strong class="text-blue-button">Payment Information:</strong> If you subscribe to a paid plan, our payment processor will collect and process your credit card details and billing information. We do not store your full credit card information on our servers.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">3. How We Use Your Information</h2>
          <p>We use the information we collect for various purposes, including to:</p>
          <ul class="list-disc pl-6 mt-2 space-y-2">
            <li>Provide, operate, and maintain our AI Service.</li>
            <li>Process your requests, generate your outputs, and manage your account.</li>
            <li>Improve the quality, safety, and accuracy of our AI models and the Service.</li>
            <li>Communicate with you, including sending service-related notifications, updates, and responding to your support inquiries.</li>
            <li>Process transactions and prevent fraudulent activity.</li>
            <li>Enforce our Terms of Service and ensure compliance with our policies.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">4. Data Retention</h2>
          <p>We retain your data only for as long as necessary to fulfill the purposes outlined in this policy.</p>
          <ul class="list-disc pl-6 mt-2 space-y-2">
              <li><strong>Account Information</strong> is retained for as long as your account is active.</li>
              <li><strong>Generated Outputs and User Content</strong> are stored temporarily to allow you to access and download them. This content may be automatically deleted after a set period (e.g., 30 days) unless you explicitly save it to a personal gallery.</li>
              <li><strong>Anonymized prompts and usage data</strong> may be retained for longer periods for the sole purpose of service improvement and statistical analysis.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">5. Information Sharing</h2>
          <p>We are committed to protecting your privacy and do not sell your personal information. We may share your information only in the following limited circumstances:</p>
          <ul class="list-disc pl-6 mt-2 space-y-2">
            <li>With trusted third-party <strong>service providers</strong> who help us operate our platform, such as cloud hosting providers and our payment processor.</li>
            <li>With <strong>legal authorities</strong> if required by law, court order, or other governmental request.</li>
            <li>In connection with a <strong>business transaction</strong>, such as a merger, acquisition, or sale of assets, where your information may be transferred as part of the deal.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">6. Your Data Rights</h2>
          <p>You have rights over your personal data. Depending on your location, these may include the right to:</p>
          <ul class="list-disc pl-6 mt-2 space-y-2">
            <li>Access the personal information we hold about you.</li>
            <li>Request corrections to any inaccurate information.</li>
            <li>Request the deletion of your personal information and account.</li>
            <li>Export your data in a machine-readable format.</li>
          </ul>
          <p class="mt-4">To exercise these rights, please contact our support team at <strong class="text-blue-button">support@www.gptoss2.com</strong>.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">7. Security</h2>
          <p>We implement robust technical and organizational security measures designed to protect your information from unauthorized access, use, or disclosure. However, no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">8. Children's Privacy</h2>
          <p>Our Service is not directed to or intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that we have collected such information, we will take steps to delete it.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">9. Changes to This Privacy Policy</h2>
          <p>We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will notify you of any material changes by posting the new policy on our website and updating the "Effective Date" at the top.</p>
        </section>

        <section>
          <h2 class="text-2xl font-bold mb-4 text-blue-h1">10. Contact Us</h2>
          <p>If you have any questions, concerns, or requests regarding this Privacy Policy, please do not hesitate to contact us at: <strong class="text-blue-button">support@www.gptoss2.com</strong></p>
        </section>

        <section class="mt-8">
          <p class="text-sm">Last updated: {{ new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) }}</p>
        </section>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useSeo } from '~/composables/useSeo';

// @ts-ignore: Nuxt macro function
definePageMeta({
  layout: false,
  name: 'privacy-policy'
})

useSeo({
    title: 'GPTOSS2 | Privacy Policy',
    description: 'Read our privacy policy for GPTOSS2, the powerful open-weight AI platform providing secure and private interactions.'
})
</script>

<style>
/* Scoped or global styles can be added here if needed, but Tailwind CSS is used primarily. */
</style>